server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/brledger"
    username: "postgres"
    password: "123"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
